variable "name" {}
variable "vpc_id" {}
variable "key_name" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "nexus_ip" {}
variable "nr_key" {}
variable "nr_acc_id" {}
variable "certificate_arn" {}
variable "domain_name" {}
variable "ansible_sg" {}
variable "bastion_sg" {}